naver:
  api:
    client-id: "G_scgdRAO_5SFme3SsbI"
    client-secret: "ijrn_rLkBU"
    url: "https://openapi.naver.com/v1/search/news.json"

server:
  port: 9091
  address: 0.0.0.0



  # application.yml
kakao:
  client-id: c4e79ae4a9131ca930285da22587695f
  client-secret: your_kakao_client_secret
  redirect-uri: http://localhost:3000/auth/callback

jwt:
  secret: your_jwt_secret_key